server:
  port: 9103
spring:
  datasource:
    url: jdbc:mysql://192.168.2.100:3306/db_monolithiot_templates?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 156001
  output:
    ansi:
      enabled: always
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 192.168.2.100:9300
      cluster-name: elk
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
path:
  staticFilePath: D:\var\static\templates
  staticServerPrefix: http://localhost/templates
logging:
  level:
    com.monolithiot.iot: debug
