server:
  port: 9103
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_monolithiot_templates?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 942698@xyes
  output:
    ansi:
      enabled: always
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: localhost:9300
      cluster-name: es
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
path:
  staticFilePath: /var/www/static0.berrontech.com/templates
  staticServerPrefix: http://static0.berrontech.com/templates
logging:
  level:
    com.monolithiot.iot: debug
