server:
  port: 7102
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_monolithiot_notification?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 156001
  output:
    ansi:
      enabled: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
logging:
  level:
    com.monolithiot.iot: debug
