spring:
  profiles:
    active: @activationProfile@
  application:
    name: notification-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    suffix: .html
    template-loader-path: classpath:/templates/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.monolithiot.com
    port: 465
    username: info@monolithiot.com
    password: MonolithInfo2018
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    virtual-host: /
    connection-timeout: 10000
    publisher-confirms: true
    template:
      mandatory: true
pagehelper:
  helper-dialect: mysql
mybatis:
  mapper-locations: classpath:mappers/*.mapper.xml
  type-aliases-package: com.monolithiot.iot.user.entity
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
sms:
  apiKey: 472dde7539dfb2c0ea2107be4d34dc63

