server:
  port: 9102
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_monolithiot_notification?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 942698@xyes
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: localhost:5672
    username: admin
    password: 111111
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
