spring:
  profiles:
    active: @activationProfile@
  application:
    name: zuul-gateway
  freemarker:
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
zuul:
  routes:
    user:
      path: /user/**
      serviceId: user-service
    notification:
      path: /notification/**
      serviceId: notification-service
    templates:
      path: /templates/**
      serviceId: templates-service

auth:
  authorizedPath:
    - /user/open/**
    - /notification/open/**
  loginPath: /user/login