server:
  port: 9101
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_monolithiot_user?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 942698@xyes
  output:
    ansi:
      enabled: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
logging:
  level:
    com.monolithiot.iot: debug
