server:
  port: 9101
spring:
  datasource:
    url: jdbc:mysql://192.168.2.100:3306/db_monolithiot_user?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: 156001
  output:
    ansi:
      enabled: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
path:
  staticFilePath: D:\var\static\user
  staticServerPrefix: http://localhost/user
logging:
  level:
    com.monolithiot.iot: debug
